### ISSUE TITLE
could not use tool

### ISSUE THREAD

**Issue by ghost** [hellerbarde/stapler#64]
Hello,

KDE Neon, latest version

```sh
sudo -H pip3 install stapler
pip3 install stapler
```

I am trying to simply delete first page
```sh
$ stapler del book.pdf 1
Traceback (most recent call last):
  File "/usr/local/bin/stapler", line 11, in <module>
    load_entry_point('stapler==0.3.3', 'console_scripts', 'stapler')()
  File "/home/alexander/.local/lib/python3.6/site-packages/staplelib/__init__.py", line 11, in main
    import stapler
ModuleNotFoundError: No module named 'stapler'
```

Can someone help to install  tool properly?

**Comment by hellerbarde** [comment]
Please try the new version of stapler on PyPI: 1.0.0b1

**Comment by corollari** [comment]
Hijacking this thread to remind that publishing the latest version to pypi would solve this kind of problems. Publishing should only require running `poetry build` and `poetry publish`, then providing your pypi credentials.
Alternatively, I could do it myself if I'm given maintainer status on the pypi project.

Also, while doing it, it'd be nice to get the token associated with the project and put it into a github secret in order to enable the CI to publish to pypi.

One of the reasons I'm asking for this is that I have a package that depends on stapler. I previously published a different stapler package (stapler3) to pypi in order to meet that dependency but, since I removed it, my package dependencies are broken. Now, I could bundle stapler directly into my package, but that doesn't seem the best solution.

**Comment by hellerbarde** [comment]
@corollari the latest version _is_ published.

**Comment by hellerbarde** [comment]
https://pypi.org/project/stapler/#history
https://pypi.org/project/stapler/1.0.0b1/

**Comment by corollari** [comment]
True, I didn't look at the project history and didn't see the last release because it was marked as a pre-release, my bad.

Why make it a pre-release tho, is it not sufficiently tested?

**Comment by hellerbarde** [comment]
@corollari I'd say now it is. I've been using it for a few weeks now. But I have changed quite a few things, also about the testing suite, and it running o python 3 now, so I was cautious. How do I put the PyPI token in the github actions thing? Then I'd do a release through the pipeline.

**Comment by Frenzie** [comment]
It's the one right above Actions, namely Secrets.

I think it should be fine if you add one called `PYPI_TOKEN` but I haven't used this kind of functionality on GH Actions specifically yet.

**Comment by corollari** [comment]
1. Obtain the token from pypi
![image](https://user-images.githubusercontent.com/32309574/76241999-e0775e80-6270-11ea-99ad-97ac3eede3ac.png)

2. Go to settings -> Secrets and a secret there, the name of the secret should be `PYPI_TOKEN`
![image](https://user-images.githubusercontent.com/32309574/76242132-1fa5af80-6271-11ea-913b-6e219bfc4690.png)

**Comment by hellerbarde** [comment]
I've done this over the weekend already. As you can see on PyPI, version 1.0.0 has been released.
